name: frederikguerin
favicon: null
layout_spectrum: 0.8303722671698779
typography_spectrum: 0.5074286074377596
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.23991560330614448
  lightness: 0.0889174232725054
  saturation: 0.7734880126081407
  rhythmicContrast: 0.8846913338638842
purpose: []
